naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: 2krbrc6i8ZHjNe2CMlVu
    secret: mDPWaJnXWl